export const PROJECTS_ACTIONS_TYPES = {
    LIST:       'PROJECTS/GET_PROJECTS_LIST',
    CREATE:     'PROJECTS/CREATE_PROJECT',
    EDIT:       'PROJECTS/EDIT_PROJECT',
    DELETE:     'PROJECTS/DELETE_PROJECT',
    FETCH_LIST: 'PROJECTS/FETCH_PROJECTS_LIST',
}

export const MICROSERVICE_ACTIONS_TYPES = {
    LIST:           'MICROSERVICE/GET_MICROSERVICES_LIST',
    ADD_TO_PROJECT: 'MICROSERVICE/ADD_MICROSERVICE_TO_PROJECT',
}
